### PR TITLE
[codex] fix Go 1.26 install by upgrading sonic

### PR DESCRIPTION
**Pull request by dolzenko**
## What changed
- upgraded the indirect `github.com/bytedance/sonic` dependency from `v1.14.1` to `v1.15.0`
- upgraded the indirect `github.com/bytedance/sonic/loader` dependency from `v0.3.0` to `v0.5.0`

## Why
Installing `archlint` with Go 1.26 failed during compilation of `github.com/bytedance/sonic/internal/rt` with:

```text
undefined: GoMapIterator
```

The project does not use `sonic` directly; it comes in transitively through `github.com/olive-io/bpmn/schema`. Updating the indirect `sonic` dependencies is enough to restore compatibility with Go 1.26.

## Validation
- `go build ./cmd/archlint`
- `go test ./...`
- `go install ./cmd/archlint`

### CODE REVIEW

**Comment by mikeshogin** [comment]
Thanks @dolzenko! Great work. We actually made the same fix in commit 2930e6d yesterday (racing with your PR), but appreciate the contribution. Merging this to keep the history clean with attribution.

**Comment by mikeshogin** [comment]
Thank you @dolzenko for this contribution\! Unfortunately we can't merge this cleanly because we made the same sonic upgrade in commit 2930e6d yesterday (racing with your work). The fix is already in main - try `go install github.com/mshogin/archlint/cmd/archlint@v1.1.0` and it should work on Go 1.26. Credit for the idea belongs to you.
